<% app_name = 'skill-tracker' %>

development:
  adapter: postgresql
  database: skill-tracker_development

test:
  adapter: postgresql
  database: skill-tracker_test

production:
  adapter: postgresql
  database: skill-tracker_production
